export const icons = [
  'icon-[openmoji--old-woman-dark-skin-tone]',
  'icon-[openmoji--old-woman-light-skin-tone]',
  'icon-[openmoji--old-woman-medium-dark-skin-tone]',
  'icon-[openmoji--old-woman-medium-light-skin-tone]',
  'icon-[openmoji--old-woman-medium-skin-tone]',
  'icon-[twemoji--old-woman]',
  'icon-[twemoji--old-woman-dark-skin-tone]',
  'icon-[twemoji--old-woman-light-skin-tone]',
  'icon-[twemoji--old-woman-medium-dark-skin-tone]',
  'icon-[twemoji--old-woman-medium-light-skin-tone]',
  'icon-[twemoji--old-woman-medium-skin-tone]',
  'icon-[noto--old-woman]',
  'icon-[noto--old-woman-dark-skin-tone]',
  'icon-[noto--old-woman-light-skin-tone]',
  'icon-[noto--old-woman-medium-dark-skin-tone]',
  'icon-[noto--old-woman-medium-light-skin-tone]',
  'icon-[noto--old-woman-medium-skin-tone]',
  'icon-[fluent-emoji--old-woman]',
  'icon-[fluent-emoji--old-woman-dark]',
  'icon-[fluent-emoji--old-woman-light]',
  'icon-[fluent-emoji--old-woman-medium]',
  'icon-[fluent-emoji--old-woman-medium-dark]',
  'icon-[fluent-emoji--old-woman-medium-light]',
  'icon-[fluent-emoji-flat--old-woman]',
  'icon-[fluent-emoji-flat--old-woman-dark]',
  'icon-[fluent-emoji-flat--old-woman-light]',
  'icon-[fluent-emoji-flat--old-woman-medium]',
  'icon-[fluent-emoji-flat--old-woman-medium-dark]',
  'icon-[fluent-emoji-flat--old-woman-medium-light]',
  'icon-[fluent-emoji-high-contrast--old-woman]',
  'icon-[noto-v1--old-woman]',
  'icon-[noto-v1--old-woman-dark-skin-tone]',
  'icon-[noto-v1--old-woman-light-skin-tone]',
  'icon-[noto-v1--old-woman-medium-dark-skin-tone]',
  'icon-[noto-v1--old-woman-medium-light-skin-tone]',
  'icon-[noto-v1--old-woman-medium-skin-tone]',
  'icon-[emojione--old-woman]',
  'icon-[emojione--old-woman-dark-skin-tone]',
  'icon-[emojione--old-woman-light-skin-tone]',
  'icon-[emojione--old-woman-medium-dark-skin-tone]',
  'icon-[emojione--old-woman-medium-light-skin-tone]',
  'icon-[emojione--old-woman-medium-skin-tone]',
  'icon-[emojione-monotone--old-woman]',
  'icon-[emojione-v1--old-woman]',
  'icon-[streamline-emojis--old-woman-1]',
  'icon-[streamline-emojis--old-woman-2]',
  'icon-[openmoji--old-man]',
  'icon-[openmoji--old-man-dark-skin-tone]',
  'icon-[openmoji--old-man-light-skin-tone]',
  'icon-[openmoji--old-man-medium-dark-skin-tone]',
  'icon-[openmoji--old-man-medium-light-skin-tone]',
  'icon-[openmoji--old-man-medium-skin-tone]',
  'icon-[twemoji--old-man]',
  'icon-[twemoji--old-man-dark-skin-tone]',
  'icon-[twemoji--old-man-light-skin-tone]',
  'icon-[twemoji--old-man-medium-dark-skin-tone]',
  'icon-[twemoji--old-man-medium-light-skin-tone]',
  'icon-[twemoji--old-man-medium-skin-tone]',
  'icon-[noto--old-man]',
  'icon-[noto--old-man-dark-skin-tone]',
  'icon-[noto--old-man-light-skin-tone]',
  'icon-[noto--old-man-medium-dark-skin-tone]',
  'icon-[noto--old-man-medium-light-skin-tone]',
  'icon-[noto--old-man-medium-skin-tone]',
  'icon-[fluent-emoji--old-man]',
  'icon-[fluent-emoji--old-man-dark]',
  'icon-[fluent-emoji--old-man-light]',
  'icon-[fluent-emoji--old-man-medium]',
  'icon-[fluent-emoji--old-man-medium-dark]',
  'icon-[fluent-emoji--old-man-medium-light]',
  'icon-[fluent-emoji-flat--old-man]',
  'icon-[fluent-emoji-flat--old-man-dark]',
  'icon-[fluent-emoji-flat--old-man-light]',
  'icon-[fluent-emoji-flat--old-man-medium]',
  'icon-[fluent-emoji-flat--old-man-medium-dark]',
  'icon-[fluent-emoji-flat--old-man-medium-light]',
  'icon-[fluent-emoji-high-contrast--old-man]',
  'icon-[noto-v1--old-man]',
  'icon-[noto-v1--old-man-dark-skin-tone]',
  'icon-[noto-v1--old-man-light-skin-tone]',
  'icon-[noto-v1--old-man-medium-dark-skin-tone]',
  'icon-[noto-v1--old-man-medium-light-skin-tone]',
  'icon-[noto-v1--old-man-medium-skin-tone]',
  'icon-[emojione--old-man]',
  'icon-[emojione--old-man-dark-skin-tone]',
  'icon-[emojione--old-man-light-skin-tone]',
  'icon-[emojione--old-man-medium-dark-skin-tone]',
  'icon-[emojione--old-man-medium-light-skin-tone]',
  'icon-[emojione--old-man-medium-skin-tone]',
  'icon-[emojione-monotone--old-man]',
  'icon-[emojione-v1--old-man]',
  'icon-[streamline-emojis--old-man-1]',
  'icon-[streamline-emojis--old-man-2]',
];

// export const icons = [
//   <span className="icon-[openmoji--old-woman] text-3xl" />,
//   <span className="icon-[openmoji--old-woman-dark-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-woman-light-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-woman-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-woman-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-woman-medium-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-woman] text-3xl" />,
//   <span className="icon-[twemoji--old-woman-dark-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-woman-light-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-woman-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-woman-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-woman-medium-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-woman] text-3xl" />,
//   <span className="icon-[noto--old-woman-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-woman-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-woman-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-woman-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-woman-medium-skin-tone] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman-light] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman-medium] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman-medium-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-woman-medium-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman-medium] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman-medium-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-woman-medium-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-high-contrast--old-woman] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-woman-medium-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-woman] text-3xl" />,
//   <span className="icon-[emojione--old-woman-dark-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-woman-light-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-woman-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-woman-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-woman-medium-skin-tone] text-3xl" />,
//   <span className="icon-[emojione-monotone--old-woman] text-3xl" />,
//   <span className="icon-[emojione-v1--old-woman] text-3xl" />,
//   <span className="icon-[streamline-emojis--old-woman-1] text-3xl" />,
//   <span className="icon-[streamline-emojis--old-woman-2] text-3xl" />,
//   <span className="icon-[openmoji--old-man] text-3xl" />,
//   <span className="icon-[openmoji--old-man-dark-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-man-light-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-man-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-man-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[openmoji--old-man-medium-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-man] text-3xl" />,
//   <span className="icon-[twemoji--old-man-dark-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-man-light-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-man-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-man-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[twemoji--old-man-medium-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-man] text-3xl" />,
//   <span className="icon-[noto--old-man-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-man-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-man-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-man-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto--old-man-medium-skin-tone] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man-light] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man-medium] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man-medium-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji--old-man-medium-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man-medium] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man-medium-dark] text-3xl" />,
//   <span className="icon-[fluent-emoji-flat--old-man-medium-light] text-3xl" />,
//   <span className="icon-[fluent-emoji-high-contrast--old-man] text-3xl" />,
//   <span className="icon-[noto-v1--old-man] text-3xl" />,
//   <span className="icon-[noto-v1--old-man-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-man-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-man-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-man-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[noto-v1--old-man-medium-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-man] text-3xl" />,
//   <span className="icon-[emojione--old-man-dark-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-man-light-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-man-medium-dark-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-man-medium-light-skin-tone] text-3xl" />,
//   <span className="icon-[emojione--old-man-medium-skin-tone] text-3xl" />,
//   <span className="icon-[emojione-monotone--old-man] text-3xl" />,
//   <span className="icon-[emojione-v1--old-man] text-3xl" />,
//   <span className="icon-[streamline-emojis--old-man-1] text-3xl" />,
//   <span className="icon-[streamline-emojis--old-man-2] text-3xl" />,
// ];
