import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import ThemeProvider from './_providers/themeProvider/themeProvider';
import Header from './_ui/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="bg-primary">
      <body className={`${inter.className} p-5`}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
